#!/usr/bin/python
################################################################################

"""
wol is named for the most intelligent inhabitant of the Hundred Acre Wood.
He will gladly manage arXiv papers for you.

Setup your WOLDIR to be where you wish, and then begin.
If not set it will use the current directory.

See /wol/README.md for more details.

"""

__title__  = "wol"
__author__ = "Sam Hall"
__email__  = "samcphall@gmail.com"
__version__ = "v2r0"

################################################################################
import os
import pickle
import re
import sys
import urllib
from random import randint
from wolArxivs import *
################################################################################

def set_dotwol(arxivs):
    with open(WolVars().dotwol, 'wb') as f:
        pickle.dump(arxivs._arxivs, f)
        pickle.dump(arxivs._config, f)
    return
################################################################################

def read_dotwol(filename=None):
    arxivs = ArXivs()
    if filename is None:
        filename = WolVars().dotwol
    if not os.path.exists(WolVars().dotwol):
        print 'Making new .wol file'
        with open(filename, 'wb') as f:
            pickle.dump({}, f)
            pickle.dump({}, f)
    else:
        with open(filename, 'rb') as f:
            arxivs.set_arxivs(pickle.load(f))
            arxivs.set_config(pickle.load(f))
    return arxivs
################################################################################

def add(arxivs, *args):
    """Add arXiv paper to wol           : wol add arXiv-paper(s) [optional tag]"""
    dir = None
    if len(args) == 0:
        print "wol add requires argument(s)"
        return arxivs
    if not ArXiv().get_arxiv_number(args[-1]) and len(args) > 1:
        dir = args[-1]
        args = args[:-1]
    for arg in args:
        arxivs.add(arg)
        if dir is not None:
            arxivs.move(arg, dir)
        else:
            print '{0}\n{1}'.format('-' * 80, arxivs.get(arg))
    print 80 * '-'
    return arxivs
################################################################################

def addwol(arxivs, *args):
    """Add another .wol file to wol     : wol addwol another-dot-wol-file"""
    for arg in args:
        new_arxivs = read_dotwol(arg)
        arxivs.add(new_arxivs)
    return arxivs
################################################################################

def find(arxivs, *args):
    """Add a paper in wol               : wol find [optional search]"""
    if len(args) == 0:
        arxivs.find('.')
    for arg in args:
        arxivs.find(arg)
    return arxivs
################################################################################

def move(arxivs, *args):
    """Move all matching papers to tag  : wol move search tag"""
    if len(args) > 1:
        dir = args[len(args) - 1]
        for arg in args[:-1]:
            arxivs.move(arg, dir)
    return arxivs
################################################################################

def show(arxivs, *args):
    """Show matching papers             : wol show search"""
    files = arxivs.find(args[0])
    cmd = '{} '.format(arxivs.viewer)
    #if len(files) > 6:
        #files = files[:6]
    for file in files:
        cmd += '"{}" '.format(file)
    if len(files) > 0:
        os.system(cmd)
    return arxivs
################################################################################

def config(arxivs, *args):
    """Show or set config               : wol config
                                             : wol config option new-setting"""
    if len(args) == 2:
        arxivs.config(args[0], args[1])
    arxivs.show_config()
    return arxivs
################################################################################

def update(arxivs, *args):
    """Ensure wol is up to date         : wol update"""
    arxivs.check()
    return arxivs
################################################################################

def delete(arxivs, *args):
    """Remove paper explicitly (1-by-1) : wol delete filename"""
    for arg in args:
        arxivs.delete(arg)
    return arxivs
################################################################################

def help(operations):
    out = '\n'
    out += "    , ,   Wol is here to help.\n"
    out += "   (o,o)    \n"
    out += "  ./)``)    \n"
    out += '----"-"---<_\n'
    out += 'Possible operations are:\n'
    out += 'Operation   Description                        Usage'
    print out
    for key, item in sorted(operations.iteritems()):
        print ' {:10s} {}'.format(key, item.__doc__)
    print "    For display problems check your config!"
    return
################################################################################

def hello(arxivs, *args):
    """Hello.                           : wol hello"""
    quotes = [
        ["... luckily Owl kept his head and told us that the",
         "Opposite of an Introduction, my dear Pooh, was a",
         "Contradiction; and, as he is very good at long words,",
         "I am sure that that's what it is."],
        ["... Owl, wise though he was in many ways, able to read",
         "and write and spell his own name WOL, yet somehow",
         "went all to pieces over delicate words like",
         "MEASLES and BUTTEREDTOAST."],
        ["And he respects Owl, because you can't help respecting",
         "anybody who can spell TUESDAY, even if he doesn't spell",
         "it right; but spelling isn't everything. There are days",
         "when spelling Tuesday simply doesn't count."],
        ["", "HIPY PAPY BTHUTHDTH THUTHDA", "         BTHUTHDY.",""]
    ]
    out = '\n'
    out += "               {}\n"
    out += "    , ,        {}\n"
    out += "   (o,o)       {}\n"
    out += "  ./)``)       {}\n"
    out += '----"-"---<_     \n'
    print out.format(*quotes[randint(0, len(quotes) - 1)])
    return arxivs
################################################################################

def info(arxivs, *args):
    """Wol related information          : wol info"""
    out = 'Wol info\n'
    out += "               Author of wol     : {}\n".format(__author__)
    out += "    , ,        Number of entries : {}\n".format(len(arxivs))
    out += "   (o,o)       WOLDIR            : {}\n".format(os.getenv('WOLDIR'))
    out += "  ./)``)       \n"
    out += '----"-"---<_   \n'
    print out
    return arxivs
################################################################################

def browse(arxivs, *args):
    """Show arXiv papers in browser     : wol search"""
    files = arxivs.find_arxivs(args[0])
    cmd = '{} '.format(arxivs.browser)
    if len(files) > 6:
        files = files[:6]
    for file in files:
        cmd += '"{}" '.format(file.web_address)
    if len(files) > 0:
        os.system(cmd)
    return arxivs
################################################################################

def put(arxivs, *args):
    """Put non arXiv document into wol  : wol path/to/file title tag"""
    #if (len(args) != 3):
        #print 'To put a paper in wol, 3 args are required:'
        #print ' 1) pdf file'
        #print ' 2) title'
        #print ' 3) directory'
    #else:
        #arxivs.put(*args)
    arxivs.put(*args)
    return arxivs

def opts(operation, *args):
    """Options parse and then run."""
    operations = {
        'add' : add,
        'addwol' : addwol,
        'move' : move,
        'find' : find,
        'show' : show,
        'config' : config,
        'update' : update,
        'del' : delete,
        'info' : info,
        'hello' : hello,
        'browse' : browse,
        'put' : put,
    }
    if operation.replace('-', '') in ['help', 'h']:
        help(operations)
        return
    if operation not in operations.keys():
        print 'Unknown operation : {}, try wol help'.format(operation)
    else:
        try:
            arxivs = read_dotwol()
            #try:
            arxivs = operations[operation](arxivs, *args)
            #except:
                #print 'Wol input error'
            set_dotwol(arxivs)
        except:
            out =  ' , ,    Wol Error in \'wol {}\'          : Usage\n'.format(operation)
            out += '(o,o)   '
            out += operations[operation].__doc__
            print out
    return
################################################################################

################################################################################
if __name__ == "__main__":
    """Run the script!"""
    args = sys.argv[1:]
    if not args:
        print 'Please give an operation'
    else:
        operation = args.pop(0)
        opts(operation, *args)

